### ISSUE TITLE
Any UMD build available at a CDN?

### ISSUE THREAD

**Issue by pateskinasy** [jeetiss/tabs#10]
Hi, thanks for this!

Any UMD build available at a CDN?

**Comment by jeetiss** [comment]
Hi, I added UMD bundle and you can use it from unpkg cdn

link 👇🏻
https://unpkg.com/@bumaga/tabs@0.2.0/dist/index.umd.js
or minified
https://unpkg.com/@bumaga/tabs@0.2.0/dist/index.umd.min.js

But i'm bundling untranspiled code right now and you can have some troubles with it

**Comment by pateskinasy** [comment]
Thanks!
