### ISSUE TITLE
Missing 'use-constant' file

### ISSUE THREAD

**Issue by LiteSoul** [jeetiss/tabs#4]
Inside index.js it seems to import:
`import useConstant from 'use-constant';`
but no such file exist.

By the way, great little library!

**Comment by jeetiss** [comment]
Thanks 🤗

This library comes untranspiled and I think thats main reason for missing 'use-constant'
I can't reproduce this error localy, can you provide CRA version or maybe codesanbox with error?

**Comment by jeetiss** [comment]
I make example with [codesandbox](https://codesandbox.io/s/tabs-with-cra-gdoqt)
seems all work

Please provide addition info about you environment

**Comment by LiteSoul** [comment]
It's working ok here, but I just thought that the file was missing by mistake. If it's intented to work that way, then perfect!
